### ISSUE TITLE
`report()` not working with `cor.test()` output in development version

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/report#206]
``` r
library(report)

cor.test(iris$Sepal.Length, iris$Sepal.Width) |>
  report()
#> Error in abs(r): non-numeric argument to mathematical function
```

<sup>Created on 2021-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Trace:

```r
8. interpret(abs(r), rules) 
7. effectsize::interpret_r(table[[estimate]], ...) at report.htest.R#99
6. report_effectsize.htest(x, ...) at report_effectsize.R#40
5. report_effectsize(x, ...) at report.htest.R#149
4. report_table.htest(x, ...) at report_table.R#58
3. report_table(x, ...) at report.htest.R#24
2. report.htest(cor.test(iris$Sepal.Length, iris$Sepal.Width)) at report.R#105
1. report(cor.test(iris$Sepal.Length, iris$Sepal.Width)) 
```

**Comment by martinBizet** [comment]
I got the same issue with CRAN version ( R 3.6.3 ; report_0.4.0 ; effectsize_0.5 )

the issue can easily be recreated like this:

```
set.seed(0)
a <- runif(10)
b <- runif(10)
report(cor.test(a, b))
```

error:
`#Error in abs(r): non-numeric argument to mathematical function`

By looking at the code "report.htest.R" it appears that the error comes from
`effectsize::interpret_r(table[[estimate]], ...)` where table[[estimate]] is coming from `effectsize::effectsize(x, verbose = FALSE, ...)`

so basically it is the same as this:
`effectsize::interpret_r(effectsize::effectsize(cor.test(a, b)))`
which indeed raise the same issue.

Interestingly, the same with a wilcox.test work well:
`effectsize::interpret_r(effectsize::effectsize(wilcox.test(a, b)))`
gives:
```
#r (rank biserial) |       95% CI | Interpretation
#-------------------------------------------------
#0.12              | [0.38, 0.56] |          small
```

The reason seems to "simply" be that **effectsize package do not support cor.test.** Indeed
`effectsize::effectsize(cor.test(a, b))`
gives:
```
#Pearson's product-moment correlation
#
#Parameter1 | Parameter2 |    r |        95% CI | t(8) |     p
#-------------------------------------------------------------
#a          |          b | 0.30 | [-0.41, 0.78] | 0.89 | 0.399
#
#Alternative hypothesis: true correlation is not equal to 0
#Warning message:
#This 'htest' method is not (yet?) supported.
#Returning 'parameters::model_parameters(model)'. 
```

By the way, do anyone know what is the correct effect size for a cor.test? Can we simply use the r value ? (I googled a bit about it and I was hoping that the report package would give me the answer...)
Look forward to have your view...
I hope my little investigation will help you !!

**Comment by martinBizet** [comment]
Oops ! I noticed this issue is redundant with issue #203 ... So, you are already on it, sorry !
So, if I understand correctly **mattansb** comments 

> Since eg cor.test() and fisher.test() already return effect sizes (r, OR) effectsize() was just reorganizing the output...

_r_ can indeed be used as effect size for cor.test, right?

Thank you for answering my comment, even before I asked it !!

Good luck with your nice package  !!

@IndrajeetPatil I guess you can close the issue ...

**Comment by IndrajeetPatil** [comment]
Thanks!

Duplicate of #203
