### ISSUE TITLE
Error message: 'find_distribution' is not an exported object from 'namespace:parameters'

### ISSUE THREAD

**Issue by GegznaV** [easystats/report#25]
**Describe the bug**

``` r
library("report")
report(iris, median = TRUE, distribution = TRUE)
#> Error: 'find_distribution' is not an exported object from 'namespace:parameters'
```

<sup>Created on 2019-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Package `report` v0.1.0

**Comment by DominiqueMakowski** [comment]
@GegznaV Sorry about that, report is currently very unstable due to breaking changes in its core dependencies. For instance, the `find_distribution` function used by report to report dataframes has been removed from the `parameters` package, breaking the report of dataframes. This will be fixed in upcoming updates of `report`... please be patient and bear with us :)

**Comment by DominiqueMakowski** [comment]
@GegznaV Just to let you know that the package has (finally) been fixed (in theory)! You will need the latest github versions of parameters and performance:

```r
devtools::install_github("easystats/performance")
devtools::install_github("easystats/parameters")
devtools::install_github("easystats/report")
```

Please do give it a try and give us a feedback ☺️ Thanks a lot!
