### ISSUE TITLE
report() issue

### ISSUE THREAD

**Issue by atnplab** [easystats/report#26]
Hi everyone,

I have got this issue with report(). I re-installed bayestestR but there is still this problem. How can I solve this?
Best
> r <- report(fit)
Error: 'rope_bounds' is not an exported object from 'namespace:bayestestR'

**Comment by DominiqueMakowski** [comment]
Hey @atnplab, I am transferring the issue here as it is actually a problem of report: the package has not been updated following the updates of its other easystats dependencies (such as bayetestR). In fact, we currently in the process of consolidating these cornerstones packages for a better, more stable and more powerful `report`. Please bear with us during this process. 

FYI, please know that you can access all the information reported by report (the R2 and the parameters characteristics) using:

```r
devtools::install_github("easystats/bayestestR")
devtools::install_github("easystats/parameters")
devtools::install_github("easystats/performance")

library(parameters)
library(performance)

library(rstanarm)
fit <- stan_glm(Sepal.Length ~ Petal.Width, data=iris)

r2(fit)
model_parameters(fit)
```

Hope it helps, do not hesitate if you have any other questions!

**Comment by DominiqueMakowski** [comment]
Should work now ☺️ #29
