### ISSUE TITLE
"successfully" spelled wrong in model_text_parameters_bayesian()

### ISSUE THREAD

**Issue by brandondey** [easystats/report#37]
`model_text_parameters_bayesian() ` prints information about the convergence of the model in the statement: 

 "The algorithm successfuly converged (Rhat = 1.000)."

Should be another "l" in there: "successfully".

**Comment by DominiqueMakowski** [comment]
Hi Brandon, thanks for the reporting of this typo and of the other two issues!

Long story short, the package is currently very much broken due to the rework of its dependencies (notable, [parameters](https://github.com/easystats/parameters) and [performance](https://github.com/easystats/performance)). Nevertheless, once `report` is roughly fixed (hopefully soon), I will let you know and you can then help us out to test, polish and improve it☺️

**Comment by brandondey** [comment]
You bet! Eager to see this thing fully functional; it’s great!

**Comment by DominiqueMakowski** [comment]
@brandondey Just to let you know that the package has (finally) been fixed (in theory)! You will need the latest github versions of parameters and performance:

```r
devtools::install_github("easystats/performance")
devtools::install_github("easystats/parameters")
devtools::install_github("easystats/report")
```

Please do give it a try and give us a feedback (and let us know if you're interested in contributing somehow) ☺️ Thanks a lot!

**Comment by DominiqueMakowski** [comment]
PS: not sure if I fixed that typo 😅
