### ISSUE TITLE
report.loo_compare docs example broken

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/report#450]
https://easystats.github.io/report/reference/report.compare.loo.html 🙈 

![image](https://github.com/easystats/report/assets/8875533/90e47b02-2023-4e19-833a-83094d3d9ab2)

**Comment by strengejacke** [comment]
I think this is an issue from downloading packages in _pkgdown_. RccpEigen cannot be found/installed for some reasons, see also https://github.com/easystats/report/actions/runs/9798384861/job/27056744608.

**Comment by rempsyc** [comment]
Ahhhh ok I was precisely wondering why some of our tests are failing with,

```
Compiling Stan program...
Error in .fun(model_code = .x1) : 
  Eigen not found; call install.packages('RcppEigen')
```

I guess there's nothing we can do about `RcppEigen` not downloading? :/

This is affecting both the test coverage and check all examples workflows. But these are not `pkgdown` workflows. So then I wonder why it doesn't download `RcppEigen` properly.

**Comment by IndrajeetPatil** [comment]
For any workflow to download a certain package, the `DESCRIPTION` file needs to specify it as a dependency, either as a direct or a recursive one. 

The way to solve this issue is to add `{RcppEigen}` to `Suggests` field in `DESCRIPTION`.

Also, we should be running these examples conditional on this package's availability.
