### ISSUE TITLE
Revising report due to changes in "parameters" package

### ISSUE THREAD

**Issue by strengejacke** [easystats/report#55]
`parameters::model_parameter()`, when using `standardize = "refit"`, no longer returns non-standardized coefficients, but only coefficients, SE and CI based on the refitted model from the standardized data. Only when standardize-method is posthoc/basic or so, then "normal" coefficients, SE and CI _and_ std. coefficients (only) are returned.

This breaks the default report method. Since standardizing is in package _effectsize_ now, I suggest calling `model_parameters()` w/o standardizing and then call `effectsize::standardize_parameters()` separately to build the report.

I can address this issue, or you can do it, if you like. But I think you have a clearer vision of what should be reported in the end.

**Comment by DominiqueMakowski** [comment]
That's on my roadmap, on the dev branch I have initiated the cleanup. The reorganization might be the occasion to streamline how report works.

In particular, I am thinking about making `report()` (for most reg models) build upon two functions, `model_table()` and `model_text()`. The former would be the combiner of performance, parameters and effectsize into a nicely displayed table, and the latter would take such table and transform it into text. As mentioned by @mattansb somewhere, the first `model_table` would be a priority indeed. There is a "basis" (the internal generic for reg models) on the dev branch, if you wanna give it a look!

**Comment by DominiqueMakowski** [comment]
I mean, to date, report has been quite unstable (mostly breaking whenever something was changed upstream) *and* a hassle to fix because of its clunky implementation. So if we make this right, then it will be easier to catch and fix all bugs. Hence, a workflow of `model_table()`+ `model_text(model_table())` = `report()` seems appropriate, because the only critical point is to make sure model_table gives the good table. Because `model_text` would be mostly generic (i.e., disconnected from upstream dependencies, only caring about the info provided to it), as in if it detects an R2, a coefficient and a CI columns it puts into a given text.

**Comment by DominiqueMakowski** [comment]
Does such a design make sense to you?

**Comment by strengejacke** [comment]
> Does such a design make sense to you?

I think sometime I need to take a closer look and get a more comprehensive picture of how report-functions work together, so I can better judge this... But you know, I believe (in) you. ^^
